spring:
    h2:
        console:
            enabled: true
    datasource:
        url: jdbc:h2:file:./database
        username: sa
        password:        
        driver-class-name: org.h2.Driver
    jpa:
        hibernate:
            ddl-auto: create-drop
        properties:
            hibernate:
                dialect: org.hibernate.dialect.H2Dialect
